
services:
  postgres_db:
    image: postgres:latest
    container_name: PostgresCont 
    restart: always
    environment:
      - POSTGRES_DB=releves-bancaires
      - POSTGRES_USER=gael
      - POSTGRES_PASSWORD=postgres123
    ports:
      - '5432:5432'
    volumes:
      - postgres_db:/var/lb/postgresql/data
    networks:
      - default

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes
    networks:
      - default
    
  # service Nuxt app version `DEV`
  nuxt_app_dev:
    build:
      context: ../depenses-nuxt-express
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ../depenses-nuxt-express:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - API_URL=http://express_api:3003
    depends_on:
      - express_api
    networks:
      - default

  express_api:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres_db
      - DB_PORT=5432
      - DB_NAME=releves-bancaires
      - DB_USER=gael
      - DB_PASSWORD=postgres123
    depends_on:
      - postgres_db
      - redis
    networks: 
      - default

volumes:
  postgres_db:
    driver: local
  redis_data:
    driver: local

# Docker Compose V2 crée automatiquement un réseau par défaut
networks:
  default:
    driver: bridge